permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: "rouge"
#markdown: kramdown
markdown: rdiscount

# Themes are encouraged to use these universal variable
# so be sure to set them if your theme uses them.
title : GHTorrent
tagline: Query Github data!
author :
  name : Georgios Gousios
  email : gousiosg@gmail.com
  github : gousiosg
  twitter : gousiosg
  feedburner :

production_url : http://www.ghtorrent.org

scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  source: ./_bibliography
  bibliography: references
  bibliography_template: "{{reference}}"

  replace_strings: true

  details_dir:    bibliography
  details_layout: bib_details.html
  details_link:   more...

  query: "@*"
